name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Eslint
        run: npm run eslint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Tests
        run: npm run test